### ISSUE TITLE
Implement a cpu suspend finisher on the ARM FVP port

### ISSUE THREAD

**Issue by achingupta** [ARM-software/tf-issues#101]
At the moment fvp_affinst_suspend_finish() reuses the 'on' finisher (see plat/fvp/fvp_pm.c file). This hides subtle differences between the two cases such as.

   1. Per-cpu distributor interface should be initialised when a cpu is powered up in response to a PSCI cpu_on request and not when it is resumed after an earlier PSCI cpu_suspend request.

This task should implement a cpu suspend finisher on the ARM FVP port to cater for such differences.

**Comment by sandrine-bailleux** [comment]
This has been addressed by commit ARM-software/arm-trusted-firmware@f14d188681
