### ISSUE TITLE
add console_flush() and clean up "\n" character handling in console_putc()

### ISSUE THREAD

**Issue by soby-mathew** [ARM-software/tf-issues#123]
The trusted firmware is using the pl011 FIFO to transmit serial data. Console_flush() is needed when we shutdown the system (or when it goes to sleep) to avoid loosing characters in the fifo/shift register. This needs to be added and invoked from trusted firmware before shutdown/sleep.

Also currently the console_putc() prepends '/r' to every '/n' character. console_putc() shouldn't take the liberty of writing additional characters. It should write 1 character and that's all it should do!

In any case, calls to console_putc() that relies on the '\n' to be converted into '\r\n' should be reviewed.

**Comment by sandrine-bailleux** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1327
