### ISSUE TITLE
FVP port should not program the CNTACR for the non-secure timer in the CNTCTLBase frame of the system timer implementation

### ISSUE THREAD

**Issue by achingupta** [ARM-software/tf-issues#170]
The FVP port has a system level generic timer accessible to the normal world at `0x2a830000`. The platform port programs the corresponding CNTACR register and sets all the bits which gives access to all aspects of this timer to the normal world. 

Trusted firmware should only enable non-secure access to this timer frame and the CNTACR by programming the CNTNSAR. Programming of the CNTACR should be done by normal world software.

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1209
