### ISSUE TITLE
Use non-identity mapping to reduce page table size

### ISSUE THREAD

**Issue by athoelke** [ARM-software/tf-issues#202]
_placeholder_

FVP: Use VA -> PA mapping for EL3 code to shrink the virtual addresses down to just 27 bits. This is large enough to identity map the SRAM at 0x4000000, and to contain the essential EL3 devices but at a non identity location. This could allow the use of a 0.5KB level 2 table rather than a 4KB level 2 table. This would almost certainly remove another 4KB from the BL3-1 RAM usage on FVP

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1594

**Comment by antonio-nino-diaz-arm** [comment]
It isn't possible to do this in FVP, now we even map more than 32 bits of address space in AArch64 and as much memory as we can in AArch32: https://github.com/ARM-software/arm-trusted-firmware/blob/72b3226fa2ae8c8fea1ec4cd86687f35c4df93ef/include/plat/arm/common/arm_def.h#L318-L328

This is only possible in simple platforms. It is done in Allwinner, for example: https://github.com/ARM-software/arm-trusted-firmware/blob/72b3226fa2ae8c8fea1ec4cd86687f35c4df93ef/plat/allwinner/common/include/platform_def.h#L42-L43
