### ISSUE TITLE
Rationalize TF UART usage in platform ports 

### ISSUE THREAD

**Issue by danh-arm** [ARM-software/tf-issues#220]
The way that UARTs are used by TF in the FVP and Juno ports is inconsistent. The FVPs have 4 UARTs available for use, UART0 - UART3. Juno also has 4 UARTs but 2 of these are SoC UARTs, which are exposed via connectors on the back panel, and 2 are FPGA UARTs, which are only accessible via headers on the motherboard (J55 and J56).

The current usage is as follows:

                    | FVPs  | Juno
--------------------|-------|-----------
SCP                 | N/A   | SoC UART1
BL1/BL2             | UART0 | FPGA UART0
BL3-1               | UART0 | FPGA UART0
BL3-2 (TSP)         | UART1 | FPGA UART1
UEFI                | UART0 | SoC UART0
Linux               | UART0 | SoC UART0

The issues with this are as follows:

*   There isn't a good reason why BL1/BL2 use a different UART to UEFI/Linux on Juno. All components on the cold boot path should use the same UART (only one of them will be running at a given time).

*   SoC UART1 on Juno is more accessible than the FPGA UARTs (i.e. is on the back panel). There is a stronger case for TF to use this than SCP (which is closed source).

*   Each independent runtime component should use a separate UART to avoid interleaved output. BL3-1 currently doesn't emit anything at runtime but is likely to in future so we should allow for this.

So the proposed changes are as follows:

                    | FVPs   | Juno
--------------------|--------|-----------
SCP                 | N/A    | FPGA UART1*
BL1/BL2             | UART0  | SoC UART0*
BL3-1 (cold boot)   | UART0  | SoC UART0*
BL3-1 (runtime)     | UART1* | SoC UART1*
BL3-2 (TSP, cold)   | UART0*  | SoC UART0*
BL3-2 (TSP, runtime) | UART2* | FPGA UART0*
UEFI                | UART0  | SoC UART0
Linux               | UART0  | SoC UART0

\* = changed UARTs

**Comment by soby-mathew** [comment]
An update to the issue description. We decided that the TSP will use the runtime console for all output because of the complexities involved in synchronous and asynchronous initialization of TSP (depending on TSP_INIT_ASYNC build flag).
