### ISSUE TITLE
Update porting guide doc for non-identity memory mappings

### ISSUE THREAD

**Issue by soby-mathew** [ARM-software/tf-issues#258]
The porting guide in the ARM Trusted Firmware mandates that the platform ports need to use identity mapped page tables. But the Trusted Firmware supports non identity mappings for Physical to Virtual addresses.

Need to modify the documentation to reflect this change.

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1207
