### ISSUE TITLE
Update porting guide for macros and functions which do not follow AAPCS

### ISSUE THREAD

**Issue by soby-mathew** [ARM-software/tf-issues#259]
There are a couple of functions and macros in the ARM Trusted Firmware which do not have the liberty
of following the ARM Architecture Program Calling Standards (AAPCS). For example, there are macros which are used by the crash reporting framework to dump the CPU state which need to be very frugal in their register usage and cannot rely on an available stack for stashing registers. 

The porting guide should be updated for these functions and macros to have the list of registers which  are free to be clobbered and the rest should be preserved.

**Comment by sandrine-bailleux** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1325
