### ISSUE TITLE
Specify the configuration of each interrupt individually

### ISSUE THREAD

**Issue by jcastillo-arm** [ARM-software/tf-issues#262]
Each platform defines its own list of secure interrupts. The interrupts included in that list are configured using default values (level-sensitive, highest priority, routed to primary cpu).

A method to specify the configuration of each interrupt is required:
- id
- priority
- type (level/edge)
- target cpu

**Comment by sandrine-bailleux** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1324
