### ISSUE TITLE
Enable building on Windows platform.

### ISSUE THREAD

**Issue by Ianto** [ARM-software/tf-issues#266]
Some projects/companies need to build their firmware from a Windows platform.
This will require several modifications:
1. Replace soft links in git repository with the file version.
2. Add/modify make files for use on Windows platform.
3. Change code to permit build with available compiler (Visual Studio)
4. Modify tools code for Windows platform.

**Comment by danh-arm** [comment]
Fixed by https://github.com/ARM-software/arm-trusted-firmware/pull/578
