### ISSUE TITLE
Some change mey some course issues in OP-TEE

### ISSUE THREAD

**Issue by prz999** [ARM-software/tf-issues#267]
Hi,

When I using the newest master branch of ARM-trusted-firmware in fvp to running OP-TEE, I can't enter the console. The fvp just stop and show
"Connected to localhost.
Escape character is '^['.
ASSERT: init_xlation_table : next_xlat <= MAX_XLAT_TABLES"
I don't know what happened. Please help me. Thanks.

Regards,
Ruizhi

**Comment by athoelke** [comment]
@prz999, can you confirm whether OP-TEE has been updated to resolve the issue with the BL3-2 base address?
