### ISSUE TITLE
Do ARM TrustZone Fireware Support ARM-v7?

### ISSUE THREAD

**Issue by xlyu** [ARM-software/tf-issues#270]
Is ARM TrustZone Fireware compatible with ARM-v7. If not, how can I  build TEE in  ARM-v7 platform, for example to test OP_TEE in FVP  Cortex A9x4.

**Comment by sammoser** [comment]
Is there any interest in contributions to support AArch32 or ARMv7-A?
Regardless of interest, would there be recommendations on how to go about it?
