### ISSUE TITLE
FVP: remove BL32_BASE definition when building without SPD support

### ISSUE THREAD

**Issue by jcastillo-arm** [ARM-software/tf-issues#287]
Basecode uses the BL32_BASE definition to load or skip the BL3-2 image. This definition is provided by the platform port; if BL32_BASE is not defined, BL3-2 image is skipped.

The FVP port always defines BL32_BASE. Consequently, when TF is built without SPD support, BL2 will try to load a BL3-2 image from the FIP and fail to find one, reporting a warning message in the console. Even in the case there was a BL3-2 image present in the FIP, it should not be loaded into memory because there is no way to transfer control to the Secure Payload without SPD support.

Consequently, BL32_BASE should not be defined when TF is built without SPD support.

**Comment by sandrine-bailleux** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1322
