### ISSUE TITLE
Add support for %p in tf_printf()

### ISSUE THREAD

**Issue by sandrine-bailleux** [ARM-software/tf-issues#292]
We often need to print addresses in the Trusted Firmware so it would be nice
if the tf_printf() function supported the %p conversion specifier.

**Comment by danh-arm** [comment]
This task should also include making use of "%p" (instead of "0x%lx").

**Comment by sandrine-bailleux** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1321
