### ISSUE TITLE
Analyse whether some data structures could be made smaller by rearranging their fields

### ISSUE THREAD

**Issue by sandrine-bailleux-arm** [ARM-software/tf-issues#293]
The compiler has to introduce some padding bits in structures to guarantee the
alignment of individual fields and the alignment of the structure as a whole.
There might be some data structures for which we could get rid of some padding
bits by rearranging the fields. This would reduce the memory footprint of the firmware.

GCC provides a build flag that would help in this exercise: `-Wpadded`.
See https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Warning-Options.html#Warning-Options
It will generate a warning message whenever padding is included in a structure.

**Comment by danh-arm** [comment]
Fixed by https://github.com/ARM-software/arm-trusted-firmware/pull/483
