### ISSUE TITLE
Compile with -mstrict-align GCC build flag

### ISSUE THREAD

**Issue by sandrine-bailleux** [ARM-software/tf-issues#294]
Alignment checks are enabled in the Trusted Firmware (through the SCTLR.A bit).
However, GCC is not aware of that decision and by default it assumes that unaligned
accesses are allowed. We should compile with the build flag `-mstrict-align` to let GCC
know that unaligned accesses are forbidden.

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1206
