### ISSUE TITLE
PL011 driver doesn't disable UART before configuring it

### ISSUE THREAD

**Issue by sandrine-bailleux** [ARM-software/tf-issues#300]
The [PL011 TRM](http://infocenter.arm.com/help/topic/com.arm.doc.ddi0183g/index.html) specifies that:

 > You must disable the UART before any of the control registers are reprogrammed.

See [section 3.3.1 Data Register, UARTDR](http://infocenter.arm.com/help/topic/com.arm.doc.ddi0183g/I52696.html).

The Trusted Firmware doesn't enforce this, as the UART is never disabled and each bootloader stage reconfigures it.

One way to fix the issue would be to disable the UART at the very beginning of the function console_core_init().

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1205
