### ISSUE TITLE
Remove IMF_READ_INTERRUPT_ID build option

### ISSUE THREAD

**Issue by achingupta** [ARM-software/tf-issues#307]
The IMF_READ_INTERRUPT_ID build option enables a feature where the interrupt ID of the highest priority pending interrupt is passed as a parameter to the interrupt handler registered for that type of interrupt. For example, in [`tspd_sel1_interrupt_handler()`](https://github.com/ARM-software/arm-trusted-firmware/blob/master/services/spd/tspd/tspd_main.c#L98) the interrupt ID is used to raise an assertion if any interrupt apart from the per-cpu secure physical timer interrupt is recieved.
When an interrupt arrives in EL3, the type of interrupt is determined in [`plat_ic_get_pending_interrupt_type()`](https://github.com/ARM-software/arm-trusted-firmware/blob/master/bl31/aarch64/runtime_exceptions.S#L93). This is done by reading the GICC_HPPIR on ARM GICv2 systems. If IMF_READ_INTERRUPT_ID is enabled, then there is an additional read of this register to return the ID of the pending interrupt. 

The state of the GIC can change between the two reads. It is possible that the original interrupt gets deasserted after the first read and another interrupt (possibly of a different type and priority) is pending at the time of the second read. In both cases an incorrect interrupt ID will be passed to the interrupt handler. This might lead to incorrect behaviour e.g. in `tspd_sel1_interrupt_handler()` an assertion would fire. Until https://github.com/ARM-software/tf-issues/issues/305 is fixed, if no interrupt is pending at the time of the second read then execution will panic. 

There are other potential implications. A normal world interrupt could be seen pending at the first read. If a secure interrupt is seen pending at the time of the second read, then it might result in the interrupt handler making an incorrect assumption about the security state of the EL where the interrupt triggered e.g. when the TSPD_ROUTE_IRQ_TO_EL3 is enabled in the release build, the `tspd_sel1_interrupt_handler()` would assume that the interrupt has originated from the normal world. This could lead to further problems.

Keeping in mind the above, it is safer to prevent such behaviour from happenning by removing the IMF_READ_INTERRUPT_ID build option. This could result in one of these two possibilities:

1.  The 'id' parameter of the interrupt handler function is marked as unused.
2.  The prototype of the interrupt handler function is changed to remove the 'id' parameter.

The rest of the changes will be relatively straightforward.

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1203
