### ISSUE TITLE
can not start the normal world linux

### ISSUE THREAD

**Issue by nicolaspippo** [ARM-software/tf-issues#316]
hi,
   I tried to build OP-TEE using FVP,I run the setup_fvp_optee.sh,and it seems everything should have been cloned and built,it displayed OP-TEE and FVP setup completed,but when I run run_foundation.sh,in FVP terminal_0,it displayed:
 ERROR : Did not get the Device tree blob(not found),
 Linux boot loader error(not found)"
 
   could you please tell me what I may do wrong ,or give me some hints that I can check out.
   thank you.

**Comment by danh-arm** [comment]
This issue tracker is for the ARM Trusted Firmware project, not the OPTEE project. I think you should post your question here instead:
https://github.com/OP-TEE/optee_os/issues
