### ISSUE TITLE
Add cache topology info to Base and Foundation FVP DTBs

### ISSUE THREAD

**Issue by sandrine-bailleux-arm** [ARM-software/tf-issues#325]
From version 4.0 onwards, the ARM64 Linux kernel expects the device tree to indicate
the cache hierarchy. Failing to provide this information results in the following warning
message to be printed by the kernel:

```Unable to detect cache hierarchy from DT for CPU x```

The FVP device trees provided in the TF source tree need to be updated to add this
information. The patch should be similar to this one:
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=7934d69abfa98392433c03136025b71972851733

**Comment by sandrine-bailleux** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1320
