### ISSUE TITLE
ARM Generic Interrupt Controller version 3.0 driver available for comment

### ISSUE THREAD

**Issue by achingupta** [ARM-software/tf-issues#326]
An early draft of the ARM GICv3 driver is available for comment @ https://github.com/ARM-software/arm-trusted-firmware/commits/rfc/arm_gicv3_driver_v1.

This driver configures the GIC to enable affinity routing for both the normal and secure worlds across all exception levels. It does not support any legacy configurations. This is a departure from the existing "one size fits all" GIC driver that takes configuration decisions at runtime on the basis of the version of ARM GIC it is running on. This driver configures the GIC under the assumption that software components at lower exception levels will use only the features introduced in the version 3.0 of the GIC architecture specification and not care about backwards compatibility. 

The driver is still under development and at least the interfaces are subject to change. In its current form, it is meant to:

1.  give partners an idea of the direction GICv3 support in Trusted Firmware is headed.
2.  receive any early feedback regarding possible inconsistencies or improvements

The driver has not been thoroughly tested. It is able to boot the Linaro tracking and the mainline kernels using a GICv3 device tree from the ARM TF repository. Both the Linaro kernel and the UEFI need changes. These have been briefly described in the last patch. The kernel boots with and without the Test Secure Payload (TSP). This proves that the power management operations work correctly and a Group1 Secure interrupt (Per-cpu Generic secure timer interrupt) is routed to and handled in S-EL1 (TSP) after pre-empting execution in Linux.

Pre-emption of the TSP during a standard SMC 'cause of a G1NS interrupt and subsequent resumption has not been tested. SGI0 and SGI6 are configured as Group0 interrupts but they are not used. Support for these code paths has been added to the TSP though.

**Comment by danh-arm** [comment]
This driver is now upstream
