### ISSUE TITLE
gicd_set_ipriorityr() has a read-modify-write data race

### ISSUE THREAD

**Issue by athoelke** [ARM-software/tf-issues#343]
This function (currently only in the legacy driver, but needed in the v2 and v3 drivers) introduces a race when this API is used dynamically by software after GIC initialisation (which is assumed to be single-CPU).

The 32-bit register accesses will modify priority for 4 interrupts, but uses a read-modify-write approach that allows concurrent changes by other CPUs or security states to the same or adjacent interrupts to corrupt or lose updates.

GICD_IPRIORITYR<n> specifically support byte addressing so that individual interrupt priorities can be atomically updated by issuing a single byte write. `gicd_set_irpriorityr()` should use this approach.

**Comment by danh-arm** [comment]
Internal ref http://jira.arm.com/browse/GENFW-1343
