### ISSUE TITLE
Secure SPI configuration is incorrect

### ISSUE THREAD

**Issue by athoelke** [ARM-software/tf-issues#344]
The code to set the interrupt priority for secure interrupts in the new GICv2 and GICv3 drivers is incorrect. The `gicd_write_ipriorityr()` function called from the secure SPI setup code in these two drivers (e.g. [`gicv2_secure_spis_configure()`](https://github.com/ARM-software/arm-trusted-firmware/blob/master/drivers/arm/gic/v2/gicv2_helpers.c#L169)) does a 32-bit write, which affects 4 interrupts at a time and assumes the value passed in has the priority for all four interrupts.

Compare this to the legacy driver which uses `gicd_set_ipriorityr()` function that computes the right field within the register. Consider using better/clearer naming for these functions to avoid such errors being hard to identify (e.g. marking 32-bit write function as a "bulk" operation or something?)

There are other issues with `gicd_set_ipriorityr()` which I raise in a separate defect #343

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1343
