### ISSUE TITLE
system_(reset|off) members of struct plat_psci_ops are undocumented

### ISSUE THREAD

**Issue by sorenb-xlnx** [ARM-software/tf-issues#346]
The [porting-guide](https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/porting-guide.md#function--plat_setup_psci_ops-mandatory) claims: "A description of each member of this structure [plat_psci_ops] is given below. But the members _system_off_ and _system_reset_ are not described.

**Comment by danh-arm** [comment]
You are right; this obviously didn't get updated when that functionality was added.
