### ISSUE TITLE
Build system doesn't support disabling all compiler optimisations

### ISSUE THREAD

**Issue by sandrine-bailleux-arm** [ARM-software/tf-issues#350]
The [TF User Guide](https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/user-guide.md#debugging-options) claims that it is possible to disable all compiler optimisations by adding extra
compiler flags like so:
```
CFLAGS='-O0' make ...
```
Actually this doesn't work.

Although it is possible to provide extra user CFLAGS like that, these are **prepended** to the standard
TF CFLAGS. In other words, the resulting CFLAGS are `-O0 -nostdinc -ffreestanding ...`. However,
the standard TF CFLAGS already include some optimisation flag (`-Os`). Therefore, when using the
above build command line, both `-O0` and `-Os` (**in this order**) are passed to gcc. According to
[GCC manual](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html),
```
If you use multiple -O options, with or without level numbers, the last such option is the one that is effective.
```
As a result, `-Os` overrides the user-provided `-O0`. To really disable compiler optimisation, the only
option is to modify the main TF Makefile, as of now.

**Comment by sandrine-bailleux** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1357
