### ISSUE TITLE
Should the RO region BL1 be a MT_DEVICE instead of MT_MEMORY when ROM is used?

### ISSUE THREAD

**Issue by Mathieu-Brcm** [ARM-software/tf-issues#370]
Hi ATF Team,

In the xla_tables.c mmap_desc() function, should there be a case for bootrom with (ATTR_DEVICE_INDEX | OSH) flag set without the XN bit set?

Or maybe we need another set of checks for MT_MEMORY case?

Regards,
-Mathieu

**Comment by danh-arm** [comment]
Hi Mathieu

I'm not quite sure what you're asking for here. MT_MEMORY is the correct memory type for ROM; MT_DEVICE should be used for uncached device memory. Currently, we expect platforms to map all code, including ROM code, as RO (which results in the XN bit being unset). We expect platforms to map other BL image data as RW (which results in the XN bit being set); we assume the hardware will prevent any write transactions to ROM.

There is certainly a case for us providing independent control of the XN bit to allow platforms to map in ROM data (or RO data in other images) as RO and Execute-Never. Is that what you are asking for?

Regards

Dan.

**Comment by Mathieu-Brcm** [comment]
Hi Dan,

I understand.
I will close this since the issue is likely on our side.

-Mathieu
