### ISSUE TITLE
Add new `plat_psci_ops_t` hook just before wfi in CPU suspend path

### ISSUE THREAD

**Issue by danh-arm** [ARM-software/tf-issues#375]
The current `pwr_domain_suspend` hook in `plat_psci_ops_t` is called with locks acquired. Some platforms may want to take additional action after this point with the guarantee that the no global data is written to after this action is taken. For example, saving BL31 state to an alternative memory location during a system suspend operation.

This task is to create a new optional hook to enable this. Also consider related additional hooks (or re-use of the same hooks) in the other psci paths.

Documentation will also need updating.

**Comment by soby-mathew** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1442

**Comment by vwadekar** [comment]
Hello,

Any update on this activity?

**Comment by danh-arm** [comment]
We intend to implement during next month, other priorities permitting.

**Comment by vwadekar** [comment]
Will go ahead with a hacked version in our downstream code as the current
ETA would put us in a tight spot.
