### ISSUE TITLE
How to generate SIP service UUID?

### ISSUE THREAD

**Issue by sorenb-xlnx** [ARM-software/tf-issues#378]
I was wondering if there is any best known method to generate a UUID for the SIP service? All documentation I found was in the SMCCC that says that any RFC4122 compliant UUID is OK. But I thought there might be some best known method to follow.

**Comment by danh-arm** [comment]
I'm not sure there is a "best known method" but `uuidgen` from a Linux shell works for me.

**Comment by sorenb-xlnx** [comment]
Then that will work for me too :)
