### ISSUE TITLE
fix compiler warning in psci_set_req_local_pwr_state

### ISSUE THREAD

**Issue by sbranden** [ARM-software/tf-issues#379]
latest GCC compiler produces a warning fixed by adding the following assert:
	assert(pwrlvl <= PSCI_MAX_PWR_LVL);

**Comment by danh-arm** [comment]
This looks like a duplicate of #347

**Comment by danh-arm** [comment]
Closing as I'm assuming this is a duplicate (which is now fixed). Please re-raise if necessary.
