### ISSUE TITLE
Boot redundancy support missing from BL1

### ISSUE THREAD

**Issue by sbranden** [ARM-software/tf-issues#383]
BL currently does not support boot redundancy.  It is necessary to look for additional image souce locations for various reasons including fail safe image updates and/or flash corruption.

The boot redundancy needs to do the following:
1) Load from the default location of the boot source.
2) If the image is not found or image corrupt check next location (platform defined) (for example,NAND or SPI or USB flash this would be a compile time increment of offset in flash, for eMMC this should be Boot Partition 2)
3) Continue checking platform defined number of locations.  If no image found reset device.

I have not implemented this in BL1 at this time but it is a necessary feature to be added.

**Comment by danh-arm** [comment]
As far as I can see, there is nothing stopping BL1 platform code from implementing this (e.g. by overriding `bl1_plat_get_image_desc()` and `plat_error_handler()`). Perhaps there is a case for adding additional support in generic BL1 code but given that all policy would need to be in platform code, it's not clear to me what value would be left in generic code. Perhaps we need to see a working platform implementation first?

**Comment by sbranden** [comment]
If there's no plan on supporting such feature we will develop internally.  It may or may not be worth our time to upstream.

**Comment by alex-nemirovsky-ca** [comment]
Have similar need as Scott again on this one. +1

**Comment by danh-arm** [comment]
OK, I'll leave this one open but we (ARM) don't currently have any plans to work on this.

**Comment by sbranden** [comment]
Don't know how to link the pull request to this issue.

https://github.com/ARM-software/arm-trusted-firmware/pull/867

**Comment by davidcunado-arm** [comment]
@sbranden add the following to the commit message:

Fixes ARM-software/tf-issues#383

**Comment by antonio-nino-diaz-arm** [comment]
Fixed in https://github.com/ARM-software/arm-trusted-firmware/pull/867
