### ISSUE TITLE
Invalid assert from GICv3 driver

### ISSUE THREAD

**Issue by jayannad** [ARM-software/tf-issues#400]
Hi,
If the platform doesn't use both G0 and G1S interrupts, it is possible that either g0_interrupt_array or  g1s_interrupt_array could be NULL. In that case, the condition to assert from gicv3_distif_init and
gicv3_rdistif_init funtions need to be modified as 
        assert(driver_data->g0_interrupt_array ||
               driver_data->g1s_interrupt_array);
instead of
        assert(driver_data->g1s_interrupt_array);
        assert(driver_data->g0_interrupt_array);

Thanks,
Jayanthi

**Comment by soby-mathew** [comment]
Yes, it seems the driver is making the assumption that both G1S and G0 interrupts are populated in `gicv3_rdistif_init()` and `gicv3_distif_init()`. So it not just a matter of modifying the assertions but also modifying the these functions to cater to this scenario (they should skip configuring G1S or G0 if the platform has not specified it).

**Comment by soby-mathew** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1495
