### ISSUE TITLE
When do you intend to do the release V1.3 ?

### ISSUE THREAD

**Issue by marcSTM** [ARM-software/tf-issues#406]
hello,
just a quick question.
When do you intend to do the release V1.3 ?
rgds
Marc

**Comment by danh-arm** [comment]
A v1.3 release is not currently scheduled. We rely on input from partners on the timing and content of releases. You can provide input here or via a private channel if you prefer.

**Comment by danh-arm** [comment]
An update on this: We are now planning to make a v1.3 release towards the end of September.
