### ISSUE TITLE
enhance eMMC driver to support CMD23

### ISSUE THREAD

**Issue by hzhuang1** [ARM-software/tf-issues#412]
CMD23 is used to configure block counts before reading/writing. With CMD23, we could always avoid to use CMD17 (single block READ), CMD24 (single block WRITE) & CMD12 (stop data transmission). We could support the two scenarios in below.
1. CMD17/CMD24 are used to read/write single block. CMD18/CMD25 + CMD12 are used to read/write multiple blocks.
2. CMD23 + CMD18/CMD25 are used to read/write single/multiple block.

**Comment by danh-arm** [comment]
Fixed by https://github.com/ARM-software/arm-trusted-firmware/pull/680
