### ISSUE TITLE
A-TF build error with gcc-5.4

### ISSUE THREAD

**Issue by zhizhouzh** [ARM-software/tf-issues#417]
Hi,

I can't build A-TF with gcc-5.4, can you give me a hint? Thank you!

My gcc version is as follows:

> $ aarch64-linux-gnu-gcc -v
> Using built-in specs.
> COLLECT_GCC=aarch64-linux-gnu-gcc
> COLLECT_LTO_WRAPPER=/home/zh/work/clfs-arm64/tools/libexec/gcc/aarch64-linux-gnu/5.4.0/lto-wrapper
> Target: aarch64-linux-gnu
> Configured with: /home/zh/work/clfs-arm64/source/gcc-5.4.0/configure --prefix=/home/zh/work/clfs-arm64/tools --build=x86_64-cross-linux-gnu --target=aarch64-linux-gnu --host=x86_64-cross-linux-gnu --with-sysroot=/home/zh/work/clfs-arm64/tools/root --enable-shared --enable-c99 --enable-linker-build-id --enable-long-long --with-arch=armv8-a --with-gnu-ld --with-gnu-as --enable-lto --enable-nls --enable-plugin --enable-multiarch --enable-languages=c,c++ --enable-__cxa_atexit --enable-threads=posix --with-system-zlib --enable-checking=release --enable-libstdcxx-time
> Thread model: posix
> gcc version 5.4.0 (GCC) 

And here is error message:

> 
> $ export CROSS_COMPILE=aarch64-linux-gnu-
> $ make PLAT=qemu all
> [........]
>   AS      plat/common/aarch64/platform_mp_stack.S
>   AS      plat/qemu/aarch64/plat_helpers.S
>   AS      bl1/aarch64/bl1_entrypoint.S
>   AS      bl1/aarch64/bl1_exceptions.S
> bl1/aarch64/bl1_exceptions.S: Assembler messages:
> bl1/aarch64/bl1_exceptions.S:53: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:59: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:65: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:71: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:81: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:87: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:93: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:99: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:118: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:124: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:130: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:136: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:146: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:152: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:158: Error: non-constant expression in ".if" statement
> bl1/aarch64/bl1_exceptions.S:164: Error: non-constant expression in ".if" statement
> make: *** [build/qemu/release/bl1/bl1_exceptions.o] Error 1
>

**Comment by vchong** [comment]
See https://github.com/ARM-software/tf-issues/issues/401.
