### ISSUE TITLE
Linux 'standby' with ATF PSCI?

### ISSUE THREAD

**Issue by yonghong-ren** [ARM-software/tf-issues#427]
"standby" and "mem" are two common Linux suspend states. "mem" is mapped to PSCI_SYSTEM_SUSPEND.  This is done in drivers/firmware/psci.c (kernel source). Is there a plan to support "standby"? I understand this is kind of outside of ATF domain. Then is there a forum for discussing Linux to PSCI interface? Thanks

**Comment by sudeep-holla** [comment]
Hi yonghong-ren,

This have be discussed in past and it was concluded that there's no strong reason
for have such support in PSCI specification. Refer [1] for details. If you still believe
that you need to support standby, then you need to take up the discussion with
PSCI specification group. You can find the details for that in the PSCI specification itself.

Regards,
Sudeep

[1] http://lists.infradead.org/pipermail/linux-arm-kernel/2015-July/356467.html

**Comment by danh-arm** [comment]
I'm closing this question. Any further discussion should happen in the ARM Linux kernel forum Sudeep mentioned or as feedback to the PSCI specification.
