### ISSUE TITLE
MDCR_EL3 not initialized in Trusted Firmware

### ISSUE THREAD

**Issue by danh-arm** [ARM-software/tf-issues#430]
Some of the bits in the `MDCR_EL3` register have an architecturally UNKNOWN reset value. Trusted Firmware currently does not initialization this register at all, which can cause unexpected trap exceptions to EL3 on CPU implementations that do not reset these bits to zero. Cortex-A73 at least is known to be affected by this.

The EL3 architectural initialization code in Trusted Firmware should initialize this register to zero, since it does not expect to handle these trap exceptions. Similarly, TF should `MDCR_EL2` to zero, at least when starting the normal world at EL1.

Finally, `HDCR` and `SDCR` should similarly be initialized in the AArch32 EL3 case.

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1628

**Comment by prime-zeng** [comment]
So this issue has been fixed,  where can i get the the patch?

**Comment by davidcunado-arm** [comment]
I'm aiming to get the patch into a PR this week.

**Comment by prime-zeng** [comment]
OK, i have met the problem already, and have a temp fix,  I'd rather to have the PR as soon as possible.

**Comment by danh-arm** [comment]
Hi @prime-zeng 

Could you confirm that PR ARM-Software/arm-trusted-firmware#754 fixes this issue for you?

Thanks

**Comment by prime-zeng** [comment]
i am test it on my platfrom,  only set MDCR_EL3 will work for us, and one more question:  Does the DACR32_EL2 also need to intialize in EL3, more general, do we have more reset unknow register need to be set in EL3?

**Comment by danh-arm** [comment]
Thanks for testing @prime-zeng.

I don't think DACR32_EL2 needs to be intialized at EL3 since:

- EL3 has no interest in the reset value of this register, although it does save and restore it.
- EL3 operation is not affected by the reset value of this register.
- EL2 code can initialize this if it wants to (or AArch32 EL1 can initialize the corresponding DACR register).

Regarding other registers, we intend to have a look through the ARM ARM for this but haven't identified any others yet. Please let us know if you think there are any others.

**Comment by davidcunado-arm** [comment]
Hi @prime-zeng 

FYI after reviewing the ARM ARM, I've created PR ARM-software/arm-trusted-firmware/pull/772 which looks to initialise any registers that have an architecturally UNKNOWN value on reset that may have an impact on system behaviour.

Thanks,

David
