### ISSUE TITLE
AArch32: PSCI Power Domain Map prints hangs in DEBUG build

### ISSUE THREAD

**Issue by yatharth-arm** [ARM-software/tf-issues#437]
For AArch32 DEBUG built, the "psci_print_power_domain_map()", in file lib/psci/psci_common.c, hangs while printing. Following is the code snippet where it hangs:
INFO("  CPU Node : MPID 0x%llx, parent_node %d,"                        
                " State %s (0x%x)\n",                                           
                (unsigned long long)psci_cpu_pd_nodes[idx].mpidr,               
                psci_cpu_pd_nodes[idx].parent_node,                             
                psci_state_type_str[state_type],                                
                psci_get_cpu_local_state_by_idx(idx));

The issue seems to be while printing the typecasted (unsigned long long)mpidr.

**Comment by soby-mathew** [comment]
Internal ref : http://jira.arm.com/browse/GENFW-1701
