### ISSUE TITLE
Aarch64 system register definitions

### ISSUE THREAD

**Issue by chinnabha** [ARM-software/tf-issues#444]
Hi,

Can someone point me to the file wherein the system register read/write definitions are present?
When I grep for them I am unable to figure out their definitions. Seems those are integrated into some binary.  

read_scr_el3()
write_scr_el3()
write_icc_sre_el3()
read_icc_sre_el3()
read_icc_hppiro_el1()
read_icc_hppir1_el1()

**Comment by sorenb-xlnx** [comment]
For aarch64 those are in https://github.com/ARM-software/arm-trusted-firmware/blob/master/include/lib/aarch64/arch_helpers.h, the 32-bit version is https://github.com/ARM-software/arm-trusted-firmware/blob/master/include/lib/aarch32/arch_helpers.h. They are implemented as macros that might make grepping fail.

**Comment by chinnabha** [comment]
Thanks to you @sorenb-xlnx for the help.
