### ISSUE TITLE
Use ARM Compiler 6 to compile Trusted Firmware

### ISSUE THREAD

**Issue by vwadekar** [ARM-software/tf-issues#460]
Have we evaluated ARM Compiler 6 as a replacement for Linaro's GCC toolchain?

**Comment by danh-arm** [comment]
We certainly don't intend to _replace_ Linaro's GCC toolchain, but supporting LLVM in general, and ARM Compiler 6 in particular, _is_ something we'd like to do. We have no firm plans for this currently but we'll consider this along with everything else.

**Comment by danh-arm** [comment]
Internal ref: https://jira.arm.com/browse/GENFW-1775

**Comment by danh-arm** [comment]
Support for this is now upstream.
