### ISSUE TITLE
ARM TF md docs are not rendering correctly on github

### ISSUE THREAD

**Issue by soby-mathew** [ARM-software/tf-issues#465]
It seems Github has recently migrated to a `formal` specification of Markdown format [1] which breaks the formatting of headers on most of our documentation. This needs to be fixed. 

[1] https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown

**Comment by danh-arm** [comment]
This is now fixed as result of moving to reSt format:
https://github.com/ARM-software/arm-trusted-firmware/pull/1011
