### ISSUE TITLE
ARM platform: Incorrect UART clock specified

### ISSUE THREAD

**Issue by AlexeiFedorov** [ARM-software/tf-issues#479]
In \include\plat\arm\soc\common\soc_css_def.h UART clocks are defined as:
#define SOC_CSS_UART0_CLK_IN_HZ		7273800
#define SOC_CSS_UART1_CLK_IN_HZ		7273800

The correct UART clock value is 7372800Hz.

**Comment by danh-arm** [comment]
Thanks for reporting. Are you going to send a patch?

**Comment by AlexeiFedorov** [comment]
Yes, but it has to go through our internal review, so might take a while.
