### ISSUE TITLE
Add ARM copyright requirement to the docs

### ISSUE THREAD

**Issue by vwadekar** [ARM-software/tf-issues#488]
After going through several reviews with ARM, it is clear that the code *must* have the ARM copyright notice to proceed with the merge process. Other copyrights are not accepted.

But the "contributing.md" does not specify this requirement. ICan you please add this req. to the relevant docs?

**Comment by vwadekar** [comment]
I think this will definitely avoid confusion e.g. #471

**Comment by danh-arm** [comment]
Fair point - we can add this.
