### ISSUE TITLE
Trusted Board boot does not work on Juno in AArch32 mode

### ISSUE THREAD

**Issue by soby-mathew** [ARM-software/tf-issues#501]
This is due to lack of free SRAM space for BL32 on JUNO. Although we don’t have BL31 for Juno AArch32, this space is still reserved by the default configuration, thus restricting space for BL32. BL32 requires close to 7 pages of SRAM while the free space is only 6 pages in TBBR build. Hence the the load of BL32 for authentication fails.

**Comment by davidcunado-arm** [comment]
Internal ref: https://jira.arm.com/browse/GENFW-1956

**Comment by danh-arm** [comment]
Fixed by https://github.com/ARM-software/arm-trusted-firmware/commit/6c401f316f94faac8e0b2fc63c112fe85e01a995#diff-b495eb9c4ac8e8bea8ca88beba351374
