### ISSUE TITLE
A53 errata documentation

### ISSUE THREAD

**Issue by nmenon** [ARM-software/tf-issues#504]
https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/cpu-specific-build-macros.rst#cpu-errata-workarounds
Documents the following:
ERRATA_A53_826319
ERRATA_A53_836870
ERRATA_A53_855873
git grep "^ERRATA_A53" .|cut -d ':' -f2|cut -d '^I' -f1|sort -u
reveals the following undocumented (?) erratas in code?
ERRATA_A53_835769 
ERRATA_A53_843419 
implemented by:
https://github.com/ARM-software/arm-trusted-firmware/commit/a94cc374ab57b80d86974f8771565d65b38403ef

@douglas-raillard-arm will be good to have them documented.

**Comment by douglas-raillard-arm** [comment]
Hi @nmenon,

Thanks for spotting this, the documentation patch is underway. If you need more information in the mean time, you can find equivalent information in ./lib/cpus/cpu-ops.mk and the full details of the errata description here: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.epm048406/index.html

Thanks,
-Douglas

**Comment by nmenon** [comment]
@douglas-raillard-arm yep, i had tracked the info down as part of code audit.. but anyways, learnt not to lean too strongly on documentation alone ;)
