### ISSUE TITLE
RK3399 redundant assigment of "twr_tmp"

### ISSUE THREAD

**Issue by JoseRivas-R** [ARM-software/tf-issues#513]
Hi,

I was reviewing the code and I found a "twr_tmp = twr_tmp" on line 778 of rk3399/drivers/dram/dram_spec_timing.c 

Comparing to the rest of lines (see image), I think is not the expected assignment. It seems it should be "twr_tmp=12".

![rockchip_rk3399](https://user-images.githubusercontent.com/7201717/29837087-80318aa6-8cf7-11e7-95da-845cb82d64c1.png)

Thank you,
Regards

**Comment by danh-arm** [comment]
Hi @rkchrome . Any comment on this?

**Comment by dbasehore** [comment]
I read through MR1 and MR2 documentation (which this value affects), and the twr_tmp = twr_tmp statement isn't a bug. 8-12 is the range where the nWR value isn't rounded to certain values such as 6, 14, and 16.
