### ISSUE TITLE
Function "pm_fpga_load" arguments different order 

### ISSUE THREAD

**Issue by JoseRivas-R** [ARM-software/tf-issues#514]
Hi,
It seems like on plat/xilinx/zynqmp/pm_service/pm_api_sys.c arguments of "pm_fpga_load" are in different order to function definition on pm_api_sys.h

On declaration: 'address_high, address_low, size, flags'
On definition: 'address_low, address_high, size, flags'

See images.

Thank you,
Regards
![pm_fpga_load-pm_api_sys c](https://user-images.githubusercontent.com/7201717/29837796-8438cca2-8cf9-11e7-8820-f995ff2da81d.png)
![pm_fpga_load-pm_api_sys h](https://user-images.githubusercontent.com/7201717/29837797-843c6a7e-8cf9-11e7-873d-962ddf5fd7e3.png)

**Comment by danh-arm** [comment]
Hi @sorenb-xlnx . Any comment on this?

**Comment by sorenb-xlnx** [comment]
Yes, seems something went wrong somewhere. While I haven't personally tested this feature, AFAIK, it is working. Hence, the header should be changed to match the definition.
If nobody beats me to it, I'll create a PR.
