### ISSUE TITLE
rockchip: static analysis failures

### ISSUE THREAD

**Issue by davidcunado-arm** [ARM-software/tf-issues#517]
@rkchrome 
With https://github.com/ARM-software/arm-trusted-firmware/pull/1070, static analysis failures were introduced into the rockchip/rk3399 platform port:

https://github.com/ARM-software/arm-trusted-firmware/pull/1070/files/dbc0f2dcc0cf4960e2a6064ddf50df9ce1513ec0#diff-0c96fe9f910983067716d1413acaebb8R1265

https://github.com/ARM-software/arm-trusted-firmware/pull/1070/files/dbc0f2dcc0cf4960e2a6064ddf50df9ce1513ec0#diff-0c96fe9f910983067716d1413acaebb8R1297

**Comment by antonio-nino-diaz-arm** [comment]
Wasn't this fixed in https://github.com/ARM-software/arm-trusted-firmware/pull/1247 ?
