### ISSUE TITLE
SVE enabled kernels crash when booted through the trusted execution path

### ISSUE THREAD

**Issue by stsquad** [ARM-software/tf-issues#520]
While testing SVE kernels I found this bug and needed to fix it to keep my test setup simple.

**Comment by davidcunado-arm** [comment]
Internal ref: https://jira.arm.com/browse/GENFW-2063

**Comment by davidcunado-arm** [comment]
The work to support / enable this new Architectural feature is planned for Q4, barring any higher priority work.

**Comment by danh-arm** [comment]
Fixed by https://github.com/ARM-software/arm-trusted-firmware/pull/1178
