### ISSUE TITLE
fip.bin's size must be 64-byte aligned for the hikey (620) platform

### ISSUE THREAD

**Issue by raw-bin** [ARM-software/tf-issues#528]
I hit this while trying to use u-boot as the BL33 payload by following the instructions [here](https://github.com/u-boot/u-boot/blob/master/board/hisilicon/hikey/README). 

The resulting fip.bin wouldn't get flashed on to the board via fastboot. The flashing process would hang the fastboot client on the host as a result of the fastboot "server" on the board locking up.

On the other hand, using uefi_bin as a BL33 payload from an edk2 build for the hikey flashed fine.

It appears that the ATF hikey fastboot USB transport expects the size of images being flashed to be 64-byte aligned in order for the built-in DMA engine to correctly transfer the image into the on-board DRAM. 

Credit to Leo Yan from Linaro to help me trace the problem down to [_this_](https://github.com/96boards-hikey/atf-fastboot/blob/master/plat/hikey/usb.c#L586) bit of the hikey specific parts of ARM TF.

BL33 as u-boot.bin results in an almost invariably 64-byte misaligned fip.bin.
BL33 as uefi_bin seems to result in a correctly aligned fip.bin although that may just be co-incidence (I haven't checked).

Padding the fip.bin image as below results in an image that gets flashed successfully and u-boot runs fine therafter:

```
size=$(du -b "$PATH_TO_FIP" | cut -f1)
pad_size=$(($(($((size + 64)) & $((~0x3f)))) - size))
dd if=/dev/zero bs=1 count=$pad_size >> $PATH_TO_FIP
```

Fixing the USB DMA transfer code would be overkill if at all possible IMO. I think what's needed is a hikey platform specific hook in the ATF build glue that fixes up the fip.bin with the right padding using something like the above snippet.

Given that BL33 payloads can be arbitrary, it may be worthwhile to just always zero-pad fip.bin to a 64-byte aligned size. Or provide a platform specific post-processing hook.

**Comment by danh-arm** [comment]
I'm assuming this is fixed by https://github.com/ARM-software/arm-trusted-firmware/pull/1204. Please re-open if not.
