### ISSUE TITLE
need some document

### ISSUE THREAD

**Issue by asdfqwrasdf** [ARM-software/tf-issues#534]
>To aid the system designer in creating a TrustZone based TEE, Arm has created a number of documents, reference software and training courses. These documents include:
>- Trusted Base System Architecture (TBSA)
>- Trusted Board Boot Requirements (TBBR)
>- TrustZone Media Protection Architecture (TZMP)

who can help to provide TBSA & TBBR & TZMP ？
thanks!

**Comment by geesun** [comment]
ARM cannot provide these documents to non-ARM partners. The correct channel to get access to these documents is for an ARM customer to contact their dedicated customer manager to set up a NDA in place (if not already). The document will then be distributed through the said customer manager.

**Comment by asdfqwrasdf** [comment]
thanks！
