### ISSUE TITLE
Incremental builds do not take makefile changes into account

### ISSUE THREAD

**Issue by swarren** [ARM-software/tf-issues#551]
ATF's build system doesn't make any build result depend on either the makefiles that define the commands that build it, or the exact command text used to generate it (like the Linux kernel does for example). This means that the following steps:

1) git clone; export CROSS_COMPILE; make PLAT=juno all
2) edit some makefile to change a parameter such as a memory address, or an erratum or feature enable
3) make PLAT=juno all

Typically fail to build anything in step 3 above, meaning that the generated ATF binary doesn't actually reflect the intent of the source tree.

This can be fixed by:
a) Making all build products depend on $(MAKEFILE_LIST). I'll send a pull request for this soon.
b) Something more advanced, such as recording the command-line that was used to generate each build product, and regenerating it if the command-line changes. The Linux kernel's build system does this for example.

**Comment by vwadekar** [comment]
@danh-arm @davidcunado-arm

Can you take a look at Stephen's PR? If you agree in principle with the changes, I will go ahead and merge it downstream.
