### ISSUE TITLE
build ARM Trusted Firmware with clang

### ISSUE THREAD

**Issue by hzhuang1** [ARM-software/tf-issues#554]
By default, ARM Trusted Firmware is built by GCC. Is there any plan to build it with CLANG?

**Comment by dp-arm** [comment]
You can already build Trusted Firmware using clang.  See https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/user-guide.rst#building-the-trusted-firmware

NOTE: It does require the GNU linker/assembler etc.  Only the compiler is switched to clang in this configuration.
