### ISSUE TITLE
malloc support in ATF

### ISSUE THREAD

**Issue by ruchi393** [ARM-software/tf-issues#556]
Hi,

I am a newbie to ATF.  Currently I don't see support of heap being available in BL2 or Bl3 code. Is the dynamic memory allocation support planned to be added in ATF ?

Regards,
Ruchika

**Comment by davidcunado-arm** [comment]
Hi there!
Dynamic memory allocation is not supported in the any of the ARM TF code. There are no plans to support Dynamic memory.

Thanks!
David
