### ISSUE TITLE
No output for build from source on arm juno r0

### ISSUE THREAD

**Issue by Emantor** [ARM-software/tf-issues#557]
Hello,

I'm trying to get my own build of the arm-trusted-firmware running on a ARM Juno r0 board.
For that:
1. I verififed that my board boots with the arm deliverable from linaro. It does, busybox and oe latest from [here](https://releases.linaro.org/members/arm/platforms/latest/) work.
2. Build my own arm-trusted firmware with the Linaro 18.01 toolchain (gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu) and:
```
make CRASH_REPORTING=1 DEBUG=1 LOG_LEVEL=50 PLAT=juno BL33=../vexpress-firmware/SOFTWARE/bl33-uboot.bin SCP_BL2=../vexpress-firmware/SOFTWARE/scp_bl2.bin all fip
```

3. Copied bl1.bin and fip.bin to the SOFTWARE directory on the sd card via the `usb_on` command

4. Contrary to my expectations I can see no output from bl1, the board just seems to hang.

Unfortunatley I don't have an arm debugger at hand to find out why i see no output on the console. I also tried different commit ids (such as the one used for atf in the linaro-deliverable) or older tagged versions.

**Comment by sandrine-bailleux-arm** [comment]
Hi @Emantor 

I am able to reproduce your issue on Juno r0 using the steps you described. I will investigate and let you know when I find anything.

Regards,
Sandrine

**Comment by sandrine-bailleux-arm** [comment]
Hello,

You need to compile with `CSS_USE_SCMI_SDS_DRIVER=1` to select the right driver to communicate with the SCP. Please have a look at [the User Guide](https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/user-guide.rst#arm-css-platform-specific-build-options) for more details about this option.

Basically, with the build options you've specified, your ARM Trusted Firmware binaries use the SCPI/BOM driver for communicating with the SCP during power management operations whereas your SCP firmware uses the SCMI/SDS communication protocol. The 2 protocols are incompatible so they fail to communicate with each other and the board cannot boot further.

Regards,
Sandrine

**Comment by Emantor** [comment]
Thank you very much, this solves the problem for me. Is this option needed for every arm juno revision? If that is the case the option should be enabled by the platform specific makefile.

**Comment by sandrine-bailleux-arm** [comment]
> Thank you very much, this solves the problem for me.

I am glad to hear it :+1: 

> Is this option needed for every arm juno revision? If that is the case the option should be enabled by the platform specific makefile.

Yes it is needed for every ARM Juno revision. There was a transition period where the Linaro release the ARM TF was using didn't provide SCP binaries with SCMI so that is why the Juno platform makefile had disabled this option by default. With the Linaro release we now advertise (i.e. 17.10) this is no longer the case so you're right, it should be enabled by default now.

I am going to submit a patch to change this default value today.
Thanks for reporting this issue.

**Comment by sandrine-bailleux-arm** [comment]
Hi @Emantor 

 > I am going to submit a patch to change this default value today.

See https://github.com/ARM-software/arm-trusted-firmware/pull/1289

**Comment by Emantor** [comment]
And its merged, thanks again :smile:
