### ISSUE TITLE
Build failed with QEMU aarch32 with AARCH_SP=optee

### ISSUE THREAD

**Issue by ldebieve** [ARM-software/tf-issues#559]
Hi,

Coming for merge of #1263 request (Dynamic Configuration Prototype), it breaks the qemu build with optee support on aarch32.
Patch:     Introduce the new BL handover interface

make ARM_ARCH_MAJOR=7 ARM_ARCH_MINOR=3 AARCH32_SP=optee ARCH=aarch32 PLAT=qemu
.....
plat/common/aarch32/plat_common.c:9:10: fatal error: platform_sp_min.h: No such file or directory
 #include <platform_sp_min.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

The file plat/common/aarch32/plat_common.c only include sp_min function and new include (platform_sp_min.h) break build. This file is not present in case of no BL32 usage.

In my opinion, this file must not be in plat/common/aarch32 as all functions are only dedicated to sp_min.

BR,

**Comment by danh-arm** [comment]
Thanks for reporting - we'll fix this
