### ISSUE TITLE
Platforms cannot override ENABLE_STACK_PROTECTOR

### ISSUE THREAD

**Issue by michpappas** [ARM-software/tf-issues#567]
Defining ENABLE_STACK_PROTECTOR in platform.mk does not cause the stack protector to be enabled. This is caused by the fact that the top-level Makefile includeds stack_protector.mk before platform.mk, while conditionals in make are evaluated during file read.

**Comment by antonio-nino-diaz-arm** [comment]
Fixed in https://github.com/ARM-software/arm-trusted-firmware/pull/1324
