### ISSUE TITLE
Looks like gicd_set_icfgr() implementation not correct for GICv3.

### ISSUE THREAD

**Issue by reply2debu** [ARM-software/tf-issues#570]
File: drivers/arm/gic/common/gic_common.c . 
Api: gicd_set_icfgr

Assuming for each interrupt 2 bit allocated in GICD_ICFGRn register. My knowledge MSB bit within 2 Bit need to set to mark interrupt edge triggered.

void gicd_set_icfgr(uintptr_t base, unsigned int id, unsigned int cfg)
{
               unsigned bit_num = id & ((1 << ICFGR_SHIFT) - 1);   **=> I think this should multiply by 2, considering 2 bit used for each interrupt in GICD_ICFGRn register.** 
               uint32_t reg_val = gicd_read_icfgr(base, id);

               /* Clear the field, and insert required configuration */
               reg_val &= ~(GIC_CFG_MASK << bit_num);
               reg_val |= ((cfg & GIC_CFG_MASK) << bit_num);    
               **=> Shifting should be (bit_num + 1) here based on GIC_INTR_CFG_LEVEL/EDGE definition considering MSB bit within 2 reserved bit need to set to mark it edge trigger. OR we can define GIC_INTR_CFG_EDGE as 0b10** 

               gicd_write_icfgr(base, id, reg_val);
}

/* Interrupt configurations */
#define GIC_INTR_CFG_LEVEL                   0
#define GIC_INTR_CFG_EDGE                    1

**Comment by jeenu-arm** [comment]
@reply2debu: please have a look at this fix.
