### ISSUE TITLE
[Question] Is there any delay function in Trusted Firmware code?

### ISSUE THREAD

**Issue by iwishguo** [ARM-software/tf-issues#578]
Hi,

I need some delay function to wait for hardware initialization in Trusted Firmware, like micro second delay or something similar. Is there any function I can use immediately?
Thanks,
Gary

**Comment by hzhuang1** [comment]
@iwishguo You can get it from drivers/delay_timer/delay_timer.c.

**Comment by iwishguo** [comment]
Thanks a lot, Haojian :)
