### ISSUE TITLE
Question about ITS

### ISSUE THREAD

**Issue by lackan** [ARM-software/tf-issues#584]
Hi experts,

We can see that in function gicv3_its_restore, that resume the ITS but keep it disable. 
```
/* Restore the ITS CTLR but leave the ITS disabled */
	gits_write_ctlr(gits_base, its_ctx->gits_ctlr &
			(~GITS_CTLR_ENABLED_BIT));
```
But I don't know where to enable it, can you tell me something about that?

**Comment by soby-mathew** [comment]
The GIC helper function you refer are meant to be used to save and restore GIC context when it loses power during a system suspend. Unfortunately, the GIC ITS cannot be fully restored from the firmware and only the linux kernel can issue the right set of ITS commands to re-initialize it. Hence the current consensus is that the firmware disables the ITS on resume from system suspend and the kernel will re-initialize the ITS on finding it disabled.

So, to answer your question, the kernel should re-intialize the ITS and enable it on wakeup from system suspend.

**Comment by lackan** [comment]
@soby-mathew OK, thanks.
