### ISSUE TITLE
Position independent support inside Arm trusted Firmware

### ISSUE THREAD

**Issue by svtripathi** [ARM-software/tf-issues#592]
1. Is there a plan or implementation going on to support relocatable / Position independent support for ATF ?

2. I know BL2 and BL31 is  position independent but it’s not relocatable.  Also I don’t see GOT relocations for those. It is true that it can be loaded anywhere and get executed. 

3. Similarly for  BL1.  We relocate the DATA and BSS section from ROM to RAM but if we have a GOT relocation implementation then the entire image can be relocatable.

**Comment by svtripathi** [comment]
Thanks Danh . As we need it early I have to start working  on this. One point is we need the dynamic relocation section (rela.dyn) not to be linked inside BL_ROM. Am I correct ? To fix up the pie at the beginning of each stage needs this section to get fixed up ?

**Comment by danh-arm** [comment]
> Am I correct?

I don't know without looking into this in more detail but what you say sounds plausible.

**Comment by soby-mathew** [comment]
@svtripathi , yes, inadditon to .got section, the .rela.dyn section would also need to be fixed up for PIE.

**Comment by antonio-nino-diaz-arm** [comment]
The PR has been merged.
