### ISSUE TITLE
Possible issue in mmap_add_region_ctx while loop

### ISSUE THREAD

**Issue by Yann-lms** [ARM-software/tf-issues#594]
In the function mmap_add_region_ctx, we can have an issue (possible infinite loop) with this while loop:
    while ((mm_cursor->base_va + mm_cursor->size - 1 == end_va)
           && (mm_cursor->size < mm->size))

This can be reached with this example, on an AARCH32 platform:

static const mmap_region_t platform_mmap[] = {
    ...
    {base_pa = 0xC0000000, base_va = 0xC0000000, size = 0x40000000, attr},
    {0}
};

Here, we'll have end_va = 0xFFFFFFFF, the max possible 32 bit address.
When mm_cursor points to the last entry {0}, we have:
mm_cursor->base_va (=0) + mm_cursor->size (=0) - 1 == end_va (0xFFFFFFFF)
which is true
and
mm_cursor->size (=0) < mm->size (=0x40000000)
which is also true.

The mm_cursor will then be incremented, and will then be outside mmap_region_t table. And undefined behaviour could occur like infinite loop.

A simple correction is to add a check on mm_cursor->size not zero, like what is done in the previous while loop.

**Comment by antonio-nino-diaz-arm** [comment]
I guess you are building for AArch32, right?

**Comment by Yann-lms** [comment]
yes

**Comment by antonio-nino-diaz-arm** [comment]
Ok, that makes sense, we've had similar problems in the past with overflows of VAs in 32-bit builds.
