### ISSUE TITLE
Introduce STMicroelectronics STM32MP1 platform

### ISSUE THREAD

**Issue by Yann-lms** [ARM-software/tf-issues#600]
STM32MP1 is a microprocessor designed by STMicroelectronics, based on a dual Arm Cortex-A7.
It is an Armv7-A platform, using dedicated code from TF-A.

I will push the first series of patches for the support of this new platform.

**Comment by danh-arm** [comment]
Fixed by https://github.com/ARM-software/arm-trusted-firmware/pull/1466
