### ISSUE TITLE
IRC/Slack channels

### ISSUE THREAD

**Issue by ldts** [ARM-software/tf-issues#607]
would it be possible to have a dedicated irc or slack channel to give visibility to design discussions as well as the platform up-streaming process?

**Comment by soby-mathew** [comment]
TF-A will soon become a Linaro community project (see https://www.trustedfirmware.org/) . Currently this is a big legal/IT hurdle to do but this is something that can be setup then trustedfirmware.org materializes. Perhaps there will be a mailing list as well.

**Comment by dp-arm** [comment]
@ldts We are looking into this, it may be possible to setup something sooner rather than later.

**Comment by dp-arm** [comment]
@ldts btw the channel has been created

**Comment by antonio-nino-diaz-arm** [comment]
Ironically, today we are having some network issues so we can't connect to freenode.
