### ISSUE TITLE
Marvell a80x0 build broken?

### ISSUE THREAD

**Issue by jeenu-arm** [ARM-software/tf-issues#612]
The steps I tried are:

```
git clone https://github.com/ARM-software/arm-trusted-firmware
git clone https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell
git clone https://github.com/MarvellEmbeddedProcessors/ble-marvell

pushd arm-trusted-firmware
make CROSS_COMPILE=aarch64-linux-gnu- PLAT=a80x0 SCP_BL2=/dev/null  \
  DEBUG=1 BLE_PATH=../ble-marvell MV_DDR_PATH=../mv-ddr-marvell V=1 fiptool all
```

But the build fails complaining about missing ``mv_ddr_if.h`` file. Are there specific branches of the external repositories that one's supposed to use?

@kostapr, please advise.

**Comment by kostapr** [comment]
For DDR sources, please use "mainline" branch.
git clone https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell -b mv_ddr-armada-atf-mainline
Or if you already cloned it,  just "git checkout mv_ddr-armada-atf-mainline"

**Comment by jeenu-arm** [comment]
OK, I tried with that branch, but link fails saying can't find ``printf``.

**Comment by kostapr** [comment]
Do you plan to run Linux kernel tests in CI or just a build tests?

**Comment by jeenu-arm** [comment]
Currently we only test that upstream platforms build successfully; no tests are run.

**Comment by kostapr** [comment]
OK, this one should fix the broken build:
https://github.com/MarvellEmbeddedProcessors/ble-marvell/commit/4dd59a313b1934d6ec8fd8ae11b11275b8ae5edc

Please use the "atf-mainline" branch on MarvellEmbeddedProcessors/ble-marvell.git

**Comment by jeenu-arm** [comment]
OK, thanks - it works now. However, I noticed that the dependencies are probably broken, and so builds with ``-j 8`` fails. But don't worry about this right now - the build system has other long-standing problems.
