### ISSUE TITLE
Removal of deprecated interfaces

### ISSUE THREAD

**Issue by soby-mathew** [ARM-software/tf-issues#613]
We are planning to remove support for deprecated platform interfaces from TF-A codebase and make a release in the coming months. This will help to sanitize the code and shed some of the baggage we are carrying to maintain compatibility (See [here](https://github.com/ARM-software/arm-trusted-firmware/blob/master/drivers/arm/gic/v3/gicv3_main.c#L71-L104) for an example).

This is an early heads-up and for most deprecated interfaces, replacing them with the non-deprecated ones should be straightforward. The deprecated interfaces can be flagged up by setting ERROR_DEPRECATED build flag to 1.

Comments welcome.

**Comment by antonio-nino-diaz-arm** [comment]
I've examined all platforms. At least, the following changes are needed:

HiKey (hikey, hikey960), @hzhuang1:
- Migrate from legacy GIC driver.

i.MX 8, @Anson-Huang:
- Migrate from legacy GIC driver.

Layerscape, @qoriq-open-source:
- Migrate from legacy GIC driver.

Marvell, @kostapr:
- Replace bl31_early_platform_setup by bl31_early_platform_setup2.

MediaTek, @mtk09422:
- Migrate from legacy GIC driver.
- Stop using ENABLE_PLAT_COMPAT=1.

NVidia, @vwadekar:
- Migrate from legacy GIC driver.
- Also, update documentation to reflect that t186 is a supported SoC.

QEMU, @jenswi-linaro:
- Replace bl31_early_platform_setup by bl31_early_platform_setup2.
- Replace bl2_early_platform_setup by bl2_early_platform_setup2.

RockChip (rk3328, rk3368, rk3399), @TonyXie06, @rockchip-linux:
- Migrate from legacy GIC driver.

**Comment by antonio-nino-diaz-arm** [comment]
I've done the migration for the Raspberry Pi 3 here: https://github.com/ARM-software/arm-trusted-firmware/pull/1530

**Comment by soby-mathew** [comment]
The porting guide/firmware design documentation needs to be updated for blx_early_platform_setup2 APIs. This will be done internally and pushed out soon.

**Comment by soby-mathew** [comment]
Please note that regarding the MULTI_CONSOLE_API, although the old console API is marked out as deprecated, we will not remove it for the upcoming release.

**Comment by antonio-nino-diaz-arm** [comment]
This PR is the one that removes the deprecated interfaces: https://github.com/ARM-software/arm-trusted-firmware/pull/1587

**Comment by soby-mathew** [comment]
closed via ARM-software/arm-trusted-firmware#1587

**Comment by antonio-nino-diaz-arm** [comment]
I've created two issues to track the remaining platforms: https://github.com/ARM-software/tf-issues/issues/633 https://github.com/ARM-software/tf-issues/issues/634
