### ISSUE TITLE
No pointer authentication support

### ISSUE THREAD

**Issue by zxombie** [ARM-software/tf-issues#629]
I have patches for FreeBSD to add support for pointer authentication on the ARM AEM model. Unfortunately I'm unable to commit them to the FreeBSD svn repo as we need the trusted firmware to support this feature as, without firmware support, the model will trap to EL3 when I enable pointer authentication and execute one of the pointer authentication instructions.

**Comment by soby-mathew** [comment]
@zxombie, Enabling ARMv8.3-PAuth feature for lower ELs is something we intend to work on during this quarter. Thanks for bringing the work in FreeBSD to our notice as we can prioritise this accordingly.
