### ISSUE TITLE
Question about selection of GCC toolchain for compiling ARM-TF

### ISSUE THREAD

**Issue by aijunsun** [ARM-software/tf-issues#644]
Hi,

When I compiled TF(v1.4) source code using linaro GCC4.8 on ARMv8.1 platform, I got compile errors due to the unsupported ARMv8.1 instructions, i.e CASA instruct in the spinlock implementation. Then I tried GCC4.9 toolchain, the build can pass.
My question is: how should I select GCC toolchain in my TF build environment? Does TF recommend the toolchain version to compile TF source code? Especially for example, TF is updated to support new ARM architecture and may requires newer toolchain to compile.

Thank you.

**Comment by davidcunado-arm** [comment]
What build options are you using?

**Comment by aijunsun** [comment]
OK, thanks for your information.
