### ISSUE TITLE
"question"  v8.2 HW_ASSISTED_COHERENCY 

### ISSUE THREAD

**Issue by sandeepbrcm** [ARM-software/tf-issues#659]
Hi,
  I understand the flag can not be set for platforms with Cortex A53  A72  anything before V8.2.
  because it assumes a PE to be coherent with out requiring any cache mnt operation during power 
  down/up by software. ie all details are taken care in HW ( the core / cluster subsystem ).
  Is this understanding correct.   
Thanks
Sandeep

**Comment by soby-mathew** [comment]
Hi Sandeep,
You are right in that the HW_ASSISTED_COHERENCY build flag is to be enabled for CPUs which are coherent out of reset and cache maintenance during power down is taken care of in Hardware. It is not tied to `ARMv8.2 architecture` but the older CPUs (like A53s) are unlikely to support this feature. This is related to micro-architecture and [DynamIQ](https://developer.arm.com/technologies/dynamiq) is an example.
