### ISSUE TITLE
Modify gicd_read_pidr2 to support Qualcomm QGIC architecture

### ISSUE THREAD

**Issue by spalepu25** [ARM-software/tf-issues#667]
**File: drivers\arm\gic\v2\gicv2_private.h
API: gicd_read_pidr2**

We are from Qualcomm and working on a project with requirement to support ATF code on Qualcomm chipset.
We have ARM compliant GICV2 architecture and also the same register mapping, so we planned to use generic ARM GIC driver instead our own GIC driver.
But, we see peripheral ID register i.e. GICD_PIDR2 offsets are different in our chipset. So, we are planning to have below logic in ARM generic GIC driver.
Can you please suggest if it can be accepted in upstream codebase ?

**Proposed implementation** –
**File: include\drivers\arm\gic_v2.h**
#define GICD_PIDR2_GICV2_QUALCOMM	U(0xFD8)
#define GICD_PIDR2_GICV2_ARM	U(0xFB8)
#define QCOM_JEP106_ID U(0x70)     
#define GICD_IIDR		U(0x0008)      
#define GICD_IIDR_IMPLEMENTOR_SHIFT	U(0)
#define GICD_IIDR_IMPLEMENTOR_MASK	U(0xfff)
**File: drivers\arm\gic\v2\gicv2_private.h**
static inline unsigned int gicd_read_pidr2(uintptr_t base)
{
  uint32_t offset = ARM_GICD_PIDR2;
  if((mmio_read_32(base + GICC_IIDR) >> GICD_IIDR_IMPLEMENTOR_SHIFT) & GICD_IIDR_IMPLEMENTOR_MASK == QCOM_JEP106_ID ) { offset = QCOM_GICD_PIDR2};
 
  return mmio_read_32(base + offset);
}

**Existing implementation** -
static inline unsigned int gicd_read_pidr2(uintptr_t base)
{
                return mmio_read_32(base + GICD_PIDR2_GICV2);

}

**Comment by soby-mathew** [comment]
Yes, should be alright. Ideally if your platform port were upstream, it could have been implemented as a build-time configuration.

**Comment by spalepu25** [comment]
Thanks for the quick response Mathew.
As you've mentioned, we can change the offsets using build time configuration as well
**File path: arm-trusted-firmware\plat\qti\qcs405\platform.mk(Qualcomm specific file)**
The following flag can be defined in the above file and can be used to differentiated ARM GICV2 offset and QGIC offset
**CFLAGS=-D GICV2_QUALCOMM**

**File: drivers\arm\gic\v2\gicv2_private.h**
static inline unsigned int gicd_read_pidr2(uintptr_t base)
{
  uint32_t val = (mmio_read_32(base + GICD_IIDR) >> GICD_IIDR_IMPLEMENTOR_SHIFT) & GICD_IIDR_IMPLEMENTOR_MASK;
  uint32_t offset = GICD_PIDR2_GICV2_ARM;
  if(val == QCOM_JEP106_ID )
  {
    offset = GICD_PIDR2_GICV2_QUALCOMM;
  }
  **#ifdef GICV2_QUALCOMM**
  offset = GICD_PIDR2_GICV2_QUALCOMM;
  **#endif**
  return mmio_read_32(base + offset);
}
Please let us know your opinion regarding the two approaches?

**Comment by soby-mathew** [comment]
Its a small change. I don't have any strong preference, but I would favour the 2nd approach as you don't have to define `QCOM_JEP106_ID` and other GICv2 platforms are not affected. You could just define `GICV2_QUALCOMM` in your platform makefile.
