### ISSUE TITLE
Next Release for TF-A

### ISSUE THREAD

**Issue by ruchi393** [ARM-software/tf-issues#671]
Hi,

What is the release cycle for TF-A repository ? When should we expect the next tag to be applied ?

Regards,
Ruchika

**Comment by antonio-nino-diaz-arm** [comment]
https://github.com/ARM-software/arm-trusted-firmware/wiki/TF-A-Release-information#id2

You will find that kind of information here.

**Comment by mcarlini** [comment]
Hi Ruchika,

please also have a look at
https://github.com/ARM-software/tf-issues/issues/680
and
https://github.com/ARM-software/tf-issues/issues/681

Code freeze on PRs GitHub is expected by next Friday 15th March.

Thanks
Matteo
