### ISSUE TITLE
Cyclomatic Complexity of less than 10

### ISSUE THREAD

**Issue by vwadekar** [ARM-software/tf-issues#673]
Cyclomatic complexity is well described in posts [1] and [2]. NVIDIA is interested in keeping this number to less than 10, as part of its safety certification effort.

We have prepared some changes downstream to fix the issues flagged by Coverity. We would like to push the relevant changes upstream. Is this something that would be beneficial to others?

[1] https://blogs.msdn.microsoft.com/zainnab/2011/05/17/code-metrics-cyclomatic-complexity/
[2] https://en.wikipedia.org/wiki/Cyclomatic_complexity

**Comment by soby-mathew** [comment]
Reducing complexity within the code base is something we would be interested in. Please raise the PR and we can review the changes.

**Comment by vwadekar** [comment]
@soby-mathew 

Sounds good.

**Comment by DavidPu** [comment]
Hello, I created a PR to try to reduce CCM for xlat_tables_map_region and xlat_tables_unmap_region functions.

**Comment by vwadekar** [comment]
I think there are some other changes required before this issue can be closed. The source of confusion might be the "fixes" comment in David's PR.

@DavidPu can you push the remaining changes as well?
