### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chenbd** [ARM-software/tf-issues#675]
The master branch compile error using the following command:
`make PLAT=fvp RESET_TO_BL31=1 ARM_LINUX_KERNEL_AS_BL33=1 PRELOADED_BL33_BASE=0xc0000000 ARM_PRELOADED_DTB_BASE=0x83e00000`

error messages:
PP bl1/bl1.ld.S
LD build/fvp/release/bl1/bl1.elf
aarch64-linux-gnu-ld.bfd: build/fvp/release/bl1/bl1.elf: Not enough room for program headers, try linking with -N
aarch64-linux-gnu-ld.bfd: final link failed: Bad value

But v1.5 tag compiles OK.

**Comment by antonio-nino-diaz-arm** [comment]
Can you try adding ``ENABLE_PIE=0``?

What version of GCC are you using?

**Comment by chenbd** [comment]
Hello,

I'm using `gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu`.

add `ENABLE_PIE=0` fixed this issue.
Thanks.

**Comment by antonio-nino-diaz-arm** [comment]
@soby-mathew

**Comment by soby-mathew** [comment]
From the looks of it, seems to be a linker issue.  Either the `-pie` option passed to linker or object files compiled with `-fpie` seems to be a problem.
