### ISSUE TITLE
Dependency between TRUSTED_BOARD_BOOT and mbedtls

### ISSUE THREAD

**Issue by ruchi393** [ARM-software/tf-issues#677]
Hi,

I recently see a patch which adds the following in the  file plat/common/plat_bl_common.c.

#if TRUSTED_BOARD_BOOT
#include <drivers/auth/mbedtls/mbedtls_config.h>
#endif

On my platform , I have a usecase where TRUSTED_BOARD_BOOT is required but I am not compiling mbedtls. This addition in the plat_bl_common.c file breaks this use case.

Can this dependency be removed from this file ?

Regards,
Ruchika

**Comment by antonio-nino-diaz-arm** [comment]
@jts-arm

**Comment by jts-arm** [comment]
Hello @ruchi393,
Could you please copy-paste the compilation error you are facing?

Thank you!
John

**Comment by ruchi393** [comment]
CC      plat/common/plat_bl_common.c
In file included from plat/common/plat_bl_common.c:14:0:
include/drivers/auth/mbedtls/mbedtls_config.h:92:10: fatal error: mbedtls/check_config.h: No such file or directory
 #include "mbedtls/check_config.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by jts-arm** [comment]
Could you please try the following? From the plat_bl_common.c file:
1) remove the mbedtls_config.h inclusion
2) remove the plat_get_mbedtls_heap() function.

Try this quick fix, please, to see if compilation succeeds.

**Comment by ruchi393** [comment]
I had tried removing the mbedtls_config.h inclusion which helps in resolving compilation issue since 
plat_get_mbedtls_heap doesn't get used in my code. 

Probably this function needs to move to some other file.

**Comment by antonio-nino-diaz-arm** [comment]
Can you try with https://github.com/ARM-software/arm-trusted-firmware/pull/1847?

**Comment by antonio-nino-diaz-arm** [comment]
Fixed in https://github.com/ARM-software/arm-trusted-firmware/pull/1847
