### ISSUE TITLE
zynqmp: PM_SET_CONFIGURATION not implemented

### ISSUE THREAD

**Issue by lucaceresoli** [ARM-software/tf-issues#678]
`PM_SET_CONFIGURATION` is the SMC call to send a configuration object to the PMU firmware on ZynqMP. It is not implemented, thus sending the configuration is not doable at runtime and requires a build-time hack.

**Comment by soby-mathew** [comment]
Closed via https://github.com/ARM-software/arm-trusted-firmware/pull/1850
