### ISSUE TITLE
query on license header

### ISSUE THREAD

**Issue by sandeepbrcm** [ARM-software/tf-issues#685]
I have a generic query on BSD-3. Please advise.  Even though its not much TF-A specific,
there are code from plat/arm which fits with/without modification to other SoC platforms.
Some implementation have replicated and renamed files/functions and some platforms may have a different or slightly resembling implementation. I understand if it is completely reusable we must raise pull request to move it to driver or plat/common . eg: scmi scpi protocol implementation, some of the standard IP drivers etc.

In order to add a platform support the code reused ( a copy in plat/xxx) from plat/arm reference should
have which header if there are considerable additions/modifications to the original file/functions.
Only:
  Copyright (c) 2018, ARM Limited and Contributors. All rights reserved
Or
  Copyright (c) 2018,  <OWNER> . All rights reserved
Or  can it also have both.
  Copyright (c) 2018, ARM Limited and Contributors. All rights reserved
  Copyright (c) 2018,  <OWNER> . All rights reserved
I see most plat/xxx  implementation maintains header as
  Copyright (c) 2018, ARM Limited and Contributors. All rights reserved
Or it depends on what exactly the file looks like. 
Thanks.

**Comment by robertovargas-arm** [comment]
After the 2.o release the policy about copyrights was changed. Before 2.0, all the files had "ARM Limited and Contributors. All rights reserved", but after it, significant modifications can incorporate Copyrights from companies different than ARM. Lines like:

      Copyright (c) 2018, . All rights reserved

seem wrong to me, because the copyright holder is lost, and it means that the copyright line has no meaning.

**Comment by sandeepbrcm** [comment]
Thanks . I omitted the name. I meant   Copyright (c) 2018, contributor-name.  All rights reserved.
But I understood that part. I understand that in case of significant contribution one can
add own copyright.  I am specifically confused with the files that are inspired / replicated from
plat/arm to plat/xxx  eg:  arm_bl2_setup.c.

Or in some cases is it even valid to have ..
Copyright (c) 2018, ARM Limited and Contributors. All rights reserved
Copyright (c) 2018, other-contributor-name. All rights reserved

**Comment by soby-mathew** [comment]
Yes, it is valid to have multiple copyright licenses in a file.
