### ISSUE TITLE
GICv2 save and restore question.

### ISSUE THREAD

**Issue by casionwoo** [ARM-software/tf-issues#688]
Hello experts,
I'm currently working on SYSTEM_SUSPEND in Hikey platform(not hikey960) which have GICv2.
Here's my question that does ATF save and restore the context of GIC?
I think when it goes to suspend power state, turning off or not is depends on platform architecture. that ATF could save and restores the context.

If ATF does save and restore the context of GIC, can you give me the hint where I can find it in the code?

**Comment by soby-mathew** [comment]
Hi @casionwoo,
Currently there is no reference code which will save and restore GICv2 context during SYSTEM_SUSPEND. On Juno, the GICv2 is in a always ON power domain and does not lose context during SYSTEM_SYSPEND. And we did not have any request to support this for GICv2 yet.

We do have the reference for save and restore on GICv3 [here](https://github.com/ARM-software/arm-trusted-firmware/blob/9a207532f8216bf83fed0891fed9ed0bc72ca450/drivers/arm/gic/v3/gicv3_main.c#L616). If you can contribute something similar to that for GICv2, that will be helpful.
