### ISSUE TITLE
Changing MPU model among STM32MP1* family

### ISSUE THREAD

**Issue by ghost** [ARM-software/tf-issues#700]
I'm working on a custom Yocto image based upon the Distribution Package from ST. 
First, I built a working image for STM32MP157C-DK2 evaluation board. Now I need to change the target MPU to STM32MP151A. About TF-A, is there something I need to tweak inside the Yocto environment?

**Comment by Yann-lms** [comment]
AFAIK, there is nothing to change in yocto for TF-A in this case. The management of SoC version is done through device tree. In your board device tree, you have to #include "stm32mp151.dtsi", instead of stm32mp157.dtsi".
