### ISSUE TITLE
Question: Multi-core reset handling

### ISSUE THREAD

**Issue by coach-bin** [ARM-software/tf-issues#714]
Hi experts,
I'm trying to port TF-A and OPTEE into multi-core platform. I'm using own SPL, and I want to port BL31 only from TF-A (ROM-SPL-BL31-..)

I have 2 questions:
1. Should I release reset of secondary cores from SPL?  
2. What address should be set for RVBAR of secondary cores?

**Comment by sandrine-bailleux-arm** [comment]
Hello,

First of all, please note that the TF-A project is no longer active on Github. It has migrated to www.trustedfirmware.org. Questions like yours should be sent to the project's mailing list instead:

https://lists.trustedfirmware.org/mailman3/lists/tf-a.lists.trustedfirmware.org/

I'll try to answer your question here on Github just for this time, though. If you need any more information after that, please post to the TF-A mailing list, where everyone can benefit and contribute to the discussion.

As you are using your own ROM and SPL (in lieu of TF-A BL1 and BL2), I believe you need to build TF-A with the RESET_TO_BL31 feature enabled. Please refer to the following page for more details:

https://trustedfirmware-a.readthedocs.io/en/latest/design/reset-design.html#using-bl31-entrypoint-as-the-reset-address

Coming back to your questions:

   - Should I release reset of secondary cores from SPL?

You can, but then you need to prevent secondary cores from progressing further until such point that the primary core has finished all its initializations. This logic needs to be implemented in your platform code within BL31, specifically in plat_secondary_cold_boot_setup().

If you don't have this synchronization mechanism in place then there is a risk that secondary cores will do things too early.

As an example, you could put secondary cores into a WFI loop until they receive a CPU_ON power management call (typically sent by Linux).

   - What address should be set for RVBAR of secondary cores?

RVBAR for secondary cores should be set to the base address of BL31. Note that in RESET_TO_BL31=1 case, BL31 is a position-independent executable so you may load wherever you need.

Best regards,
Sandrine

**Comment by coach-bin** [comment]
@sandrine-bailleux-arm Thanks for your feedback. I'll look into the code more and if I have any additional questions, I'll ask them via the mailing list.
