### ISSUE TITLE
Implement a Trusted Watchdog

### ISSUE THREAD

**Issue by danh-arm** [ARM-software/tf-issues#74]
The TF cold boot path must make use of a Trusted Watchdog to prevent the platform from hanging in case of erroneous initialization. This is especially important for the Trusted Board Boot story.

Although, the Trusted Watchdog itself is platform specific, there will need to be a generic interface to this that all platforms must implement.

**Comment by jcastillo-arm** [comment]
Fix: ARM-software/arm-trusted-firmware@7b4c1405
