### ISSUE TITLE
Demonstrate secure world usage of TZC configured trusted DRAM on Base FVP

### ISSUE THREAD

**Issue by danh-arm** [ARM-software/tf-issues#82]
The Base FVP has a TZC-400 that allows partitioning of DRAM into trusted and non-trusted regions. Although we normally expect a TSP to execute from trusted SRAM, we expect real Trusted OS applications to execute from a trusted DRAM region. Therefore it would be useful to optionally demonstrate configuration of the TZC with execution of secure world code (e.g. a Test Secure-EL0 Application) from a trusted DRAM region.

Note: Using a TZC configured trusted region of main DRAM is different from using the statically configured trusted DRAM available in the FVPs (at 0x00_0600_0000).

Note: This implies that less non-trusted DRAM will be available to normal world software. There will need to be some way of passing the available extents of non-trusted DRAM to the non-trusted firmware (BL3-3). The BL2 -> BL3-1 handover interface will need to handle this situation.

**Comment by athoelke** [comment]
We now support execution of the TSP from dram, see ARM-software/arm-trusted-firmware@6fd9eaf36ee26a2625238c7e153bbe7714369889
