### ISSUE TITLE
Free memory used by routines and data only during cold boot

### ISSUE THREAD

**Issue by danh-arm** [ARM-software/tf-issues#83]
The code and data not used after cold boot should be reclaimed for use by other secure software (e.g. by placing these parts in separate linker sections).

Note: Reclaiming BL1 data memory is covered by #75 and BL2 code/data is already reclaimed after cold boot. Therefore this issue primary covers BL3-1 cold boot code/data, although there are also potential savings in the TSP (BL3-2).

Note: There might be come conflict between fixing this issue and #80.

**Comment by antonio-nino-diaz-arm** [comment]
https://github.com/ARM-software/arm-trusted-firmware/pull/1603
