### ISSUE TITLE
FIP tool: Add support for extracting components

### ISSUE THREAD

**Issue by sandrine-bailleux-arm** [ARM-software/tf-issues#86]
Currently the FIP tool can add or update an entry in a FIP file. It would be nice to also be able to extract a component (e.g. BL2 image) from an existing FIP file using the FIP tool.

**Comment by sandrine-bailleux** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-1362

**Comment by danh-arm** [comment]
Fixed by https://github.com/ARM-software/arm-trusted-firmware/pull/582
