### ISSUE TITLE
Implement support for preserving FP/SIMD context during world switches

### ISSUE THREAD

**Issue by achingupta** [ARM-software/tf-issues#93]
Like system and general purpose register context, the floating point register context for each security state needs to be preserved during a switch from one security state to another. This is required only if the software in each security state is using the floating point unit. The current implementation assumes that this is not the case.

This task should add the relevant support to the runtime services framework in EL3 under the assumption that EL3 itself does not use the floating point unit. The implementation should work even when normal and secure world software at lower exception levels is running in different execution states i.e. aarch32 and aarch64.

**Comment by achingupta** [comment]
We would need some TFTF tests and TSP instrumentation to use FP regs. to ensure that the context is indeed preserved correctly.

**Comment by danh-arm** [comment]
Internal ref: http://jira.arm.com/browse/GENFW-513

**Comment by soby-mathew** [comment]
CTX_INCLUDE_FPREGS build flag in TF-A is solving this problem in EL3. The secure world can implement their own save and restore primitives of floating point registers irrespective of EL3. Hence closing this issue.
